# Generated by Django 6.0.5 on 2026-05-30 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tên ngân sách')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền ngân sách')),
                ('remain', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền còn lại')),
                ('loop', models.BooleanField(default=False, verbose_name='Tự động lặp lại')),
                ('fromDate', models.DateField(verbose_name='Ngày bắt đầu')),
                ('toDate', models.DateField(verbose_name='Ngày kết thúc')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Ngân sách',
                'verbose_name_plural': 'Danh sách ngân sách',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Nội dung thông báo')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Liên kết (Deeplink)')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('isRead', models.BooleanField(default=False, verbose_name='Đã đọc')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Danh sách thông báo',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
                ('type', models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi tiêu')], max_length=10, verbose_name='Loại giao dịch')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Danh sách giao dịch',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tên ví')),
                ('type', models.CharField(max_length=50, verbose_name='Loại ví')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Số dư')),
            ],
            options={
                'verbose_name': 'Ví',
                'verbose_name_plural': 'Danh sách ví',
            },
        ),
        migrations.CreateModel(
            name='Budget_Wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.budget', verbose_name='Ngân sách')),
            ],
            options={
                'verbose_name': 'Liên kết Ngân sách - Ví',
                'verbose_name_plural': 'Liên kết Ngân sách - Ví',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('type', models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi tiêu')], max_length=10, verbose_name='Loại danh mục')),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='expenses.category', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh sách danh mục',
            },
        ),
    ]
