# Generated by Django 6.0.5 on 2026-05-30 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='budget',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='expenses.category', verbose_name='Danh mục áp dụng'),
        ),
        migrations.AddField(
            model_name='notification',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='categoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='expenses.category', verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='walletId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expenses.wallet', verbose_name='Ví giao dịch'),
        ),
        migrations.AddField(
            model_name='budget_wallets',
            name='walletId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.wallet', verbose_name='Ví'),
        ),
        migrations.AddField(
            model_name='budget',
            name='wallets',
            field=models.ManyToManyField(related_name='budgets', through='expenses.Budget_Wallets', to='expenses.wallet', verbose_name='Các ví áp dụng'),
        ),
        migrations.AlterUniqueTogether(
            name='budget_wallets',
            unique_together={('budgetId', 'walletId')},
        ),
    ]
