# Generated by Django 6.0.5 on 2026-05-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Thời gian tạo'),
        ),
    ]
